### ISSUE TITLE
Are the trajectories in your publications publicly available?

### ISSUE THREAD

**Issue by RodenLuo** [mummi-framework/mummi-ras#1]
Hi, Congrats on the success, and huge thanks for making it open source. I wonder whether the trajectories in your publications are publicly available. Or are there any demo trajectories? 

I am [a Ph.D. student at KAUST](https://cemse.kaust.edu.sa/people/person/deng-luo), using computer graphics to build and visualize mesoscale biology models, such as [SARS-CoV-2](https://www.nanovis.org/SARS-CoV-2-model.html) and [bacteriophage T4](https://www.nanovis.org/T4-model.html). If possible, I (and my colleagues) would like to perform (multiscale, multi-representation, multi-granularity) visualization research on the trajectories you generated. 

Many thanks,
Roden

**Comment by FrankD412** [comment]
Hi @RodenLuo -- we recently got our data released for the initial campaign we performed (the data specified in our SC19 paper). You can find those data sets here:

- [MuMMI Splash Run 2](https://modac.cancer.gov/assetDetails?dme_data_id=NCI-DME-MS01-10699274)
- [MuMMI Splash Run 4](https://modac.cancer.gov/assetDetails?dme_data_id=NCI-DME-MS01-10699461)

These datasets contain macro level and coarse grained trajectories that you could visualize.

Please let us know if you need any other information.

**Comment by RodenLuo** [comment]
Hi @FrankD412, THANKS very much! These should be more than enough for a pilot study. But in case the later campaigns' will be released, it would be also great if you can make a notice here too by then.
